//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace Yahoo.API.LocalSearchResponse {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:lcl")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:yahoo:lcl", IsNullable=false)]
    public class ResultSet {
        
        /// <remarks/>
        public string ResultSetMapUrl;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result")]
        public ResultType[] Result;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalResultsAvailable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalResultsReturned;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string firstResultPosition;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:lcl")]
    public class ResultType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string State;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public string Rating;
        
        /// <remarks/>
        public DistanceType Distance;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string ClickUrl;
        
        /// <remarks/>
        public string MapUrl;
        
        /// <remarks/>
        public string BusinessUrl;
        
        /// <remarks/>
        public string BusinessClickUrl;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:lcl")]
    public class DistanceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DistanceMeasureType.miles)]
        public DistanceMeasureType unit = DistanceMeasureType.miles;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:lcl")]
    public enum DistanceMeasureType {
        
        /// <remarks/>
        miles,
    }
}
