//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
namespace Yahoo.API.VideoSearchResponse {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:srchmv")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:yahoo:srchmv", IsNullable=false)]
    public class ResultSet {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Result")]
        public ResultType[] Result;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalResultsAvailable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string totalResultsReturned;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string firstResultPosition;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:srchmv")]
    public class ResultType {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string Summary;
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        public string ClickUrl;
        
        /// <remarks/>
        public string RefererUrl;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string FileSize;
        
        /// <remarks/>
        public string FileFormat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Height;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Width;
        
        /// <remarks/>
        public System.Decimal Duration;
        
        /// <remarks/>
        public bool Streaming;
        
        /// <remarks/>
        public string Channels;
        
        /// <remarks/>
        public ThumbnailType Thumbnail;
        
        /// <remarks/>
        public string Publisher;
        
        /// <remarks/>
        public string Restrictions;
        
        /// <remarks/>
        public string Copyright;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:yahoo:srchmv")]
    public class ThumbnailType {
        
        /// <remarks/>
        public string Url;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Height;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Width;
    }
}
